web:
  build: .
  ports:
    - "8080:8080"
  environment:
    DB: jdbc:postgresql://db/fhir
    PGPASSWORD: fhir
    AUTH: false
  links:
    - db:db
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: fhir
    POSTGRES_USER: fhir
